### ISSUE TITLE
Error in decoration provider NeogitStatusDecor.end:

### ISSUE THREAD

**Issue by zer09** [NeogitOrg/neogit#1064] opened 2023-12-24 01:29 UTC
### Description

After you exit in Neogit this error is shown.

```lua
Error in decoration provider NeogitStatusDecor.end:
Error executing lua: ...e/gc/.local/share/nvim/lazy/neogit/lua/neogit/status.lua:1351: Invalid buffer id: 4
stack traceback:
        [C]: in function 'get_changedtick'
        ...e/gc/.local/share/nvim/lazy/neogit/lua/neogit/status.lua:1351: in function 'frame_key'
        ...e/gc/.local/share/nvim/lazy/neogit/lua/neogit/status.lua:1361: in function <...e/gc/.local/share/nvim/lazy/neogit/lua/neogit/status.lua:1360>
```

### Neovim version

NVIM v0.10.0-dev-1938+g242261d4e
Build type: Release
LuaJIT 2.1.1702233742

### Operating system and version

OpenSuse Tumbleweed

### Steps to reproduce

1. Open `Neogit`
2. Close `Neogit` by pressing `q`

### Expected behavior

There is should be no error after you exit on Neogit.

### Actual behavior

Error was shown

### Minimal config

```Lua
return {
	"NeogitOrg/neogit",
	dependencies = {
		"nvim-lua/plenary.nvim", -- required
		"sindrets/diffview.nvim", -- optional - Diff integration

		-- Only one of these is needed, not both.
		"nvim-telescope/telescope.nvim", -- optional
		"ibhagwan/fzf-lua", -- optional
	},
	config = true,
}
```

**Comment by CnsMaple** [comment] 2023-12-24 06:14
same question

**Comment by AThePeanut4** [comment] 2023-12-24 14:01
@CKolkey I'm getting a very similar error, on both `master` and `nightly`. I'm running the latest neovim dev version (v0.10.0-dev-1947+gab2aad509d).

It happens after viewing a commit (`<CR>` on a commit), closing the Commit View window (`q`), and then moving the cursor. On `master`, the specific error is
```
Error in decoration provider NeogitBufferViewDecorNeogitCommitView.end:
Error executing lua: .../.local/share/nvim/lazy/neogit/lua/neogit/lib/buffer.lua:520: Invalid buffer id: 54
stack traceback:
        [C]: in function 'get_changedtick'
        .../.local/share/nvim/lazy/neogit/lua/neogit/lib/buffer.lua:520: in function 'frame_key'
        .../.local/share/nvim/lazy/neogit/lua/neogit/lib/buffer.lua:530: in function <.../.local/share/nvim/lazy/neogit/lua/neogit/lib/buffer.lua:529>
```
On `nightly`, the error is very slightly different:
```
Error in decoration provider neogit-buffer-26-ViewDecor.end:
Error executing lua: .../.local/share/nvim/lazy/neogit/lua/neogit/lib/buffer.lua:577: Invalid buffer id: 26
stack traceback:
        [C]: in function 'get_changedtick'
        .../.local/share/nvim/lazy/neogit/lua/neogit/lib/buffer.lua:577: in function 'frame_key'
        .../.local/share/nvim/lazy/neogit/lua/neogit/lib/buffer.lua:587: in function <.../.local/share/nvim/lazy/neogit/lua/neogit/lib/buffer.lua:586>
```

**Comment by CKolkey** [comment] 2023-12-24 14:21
Damn. Alright, I'll be able to take a look sometime in the next few days. Holidays, and all that :)

**Comment by AThePeanut4** [comment] 2023-12-24 14:42
Simply `pcall`ing `buffer:get_changedtick()` in the same way as #1065 seems to at least get rid of the error for me (this diff is on `nightly`):
```diff
diff --git a/lua/neogit/lib/buffer.lua b/lua/neogit/lib/buffer.lua
index ec099527..9977e5c6 100644
--- a/lua/neogit/lib/buffer.lua
+++ b/lua/neogit/lib/buffer.lua
@@ -574,7 +574,12 @@ function Buffer.create(config)
 
     buffer:call(function()
       local function frame_key()
-        return table.concat { fn.line("w0"), fn.line("w$"), fn.getcurpos()[2], buffer:get_changedtick() }
+        local ok, tick = pcall(buffer.get_changedtick, buffer)
+        if ok then
+          return table.concat { fn.line("w0"), fn.line("w$"), fn.getcurpos()[2], tick }
+        else
+          return table.concat { fn.line("w0"), fn.line("w$"), fn.getcurpos()[2], "0" }
+        end
       end
 
       local last_frame_key = frame_key()
```
No idea if the change is correct or makes sense here, but the error at least goes away. Currently, once the error message appears, clicking any key just re-triggers the error, so it makes neovim entirely unusable.

**Comment by AThePeanut4** [comment] 2023-12-24 22:45
> Yeah, just didn't have a chance to merge master into nightly. I have now :)

#1065 doesn't fix my issue, unfortunately - that's in `status.lua` whereas my error is coming from `lib/buffer.lua`. My fix above is basically just making the same change as #1065 but in a different file.

I've also added a test `print()` inside `frame_key()` just to see when the function is actually being called, like so:
```diff
diff --git a/lua/neogit/lib/buffer.lua b/lua/neogit/lib/buffer.lua
index ec09952..e5528f7 100644
--- a/lua/neogit/lib/buffer.lua
+++ b/lua/neogit/lib/buffer.lua
@@ -573,8 +573,17 @@ function Buffer.create(config)
     buffer:create_namespace("ViewDecor")
 
     buffer:call(function()
+      local i = 0
+
       local function frame_key()
-        return table.concat { fn.line("w0"), fn.line("w$"), fn.getcurpos()[2], buffer:get_changedtick() }
+        local ok, tick = pcall(buffer.get_changedtick, buffer)
+        print("call", buffer.handle, i)
+        i = i + 1
+        if ok then
+          return table.concat { fn.line("w0"), fn.line("w$"), fn.getcurpos()[2], tick }
+        else
+          return table.concat { fn.line("w0"), fn.line("w$"), fn.getcurpos()[2], "0" }
+        end
       end
 
       local last_frame_key = frame_key()

```
And from that I can see that the `frame_key` function is called every time the cursor moves or anything happens onscreen, even after the commit view and all other neogit views have been closed. I can't imagine this is intentional, so adding `pcall` isn't fixing the root cause, just the symptom.

**Comment by CKolkey** [comment] 2023-12-25 09:35
Yeah, good point. That `frame_key` thing was one of the first things I added to this codebase, and needless to say, I've learned a lot since then. My thinking was to do something like rate-limit redrawing, but I don't think that really makes any difference, and clearly causes some issues. So, let's just ditch the idea, and see how that goes.

https://github.com/NeogitOrg/neogit/pull/1068

**Closed** 2023-12-25 09:36 UTC
Labels: bug
