### ISSUE TITLE
Bug on pushing with email&password

### ISSUE THREAD

**Issue by timsofteng** [NeogitOrg/neogit#82] opened 2021-03-26 19:43 UTC
Catch this bug
![image](https://user-images.githubusercontent.com/51912173/112684792-39b23000-8e7c-11eb-8d06-59173c0a27d7.png)

keys doesn't works

**Comment by TimUntersberger** [comment] 2021-04-06 09:20
What is your setup and what actions did you take to reproduce this bug?

**Comment by denilson020898** [comment] 2021-04-18 03:34
![Screenshot 2021-04-18 102931](https://user-images.githubusercontent.com/24517135/115133253-fb4e0200-a030-11eb-8ad0-102ce44caa3f.png)

I get this too.
I cloned my own repo to another machine over HTTPS, which requires me to enter my github username and password
to be able to push.

Setup:
- NVIM v0.5.0-dev+1260-ga6504ec33
- WSL2 Linux Ubuntu 20.04

Steps:
- :Neogit
- stage all, commit, write commit message, :wq
- choose push with P, then u for upstream
- hit the bug

Ty

**Comment by TimUntersberger** [comment] 2021-06-15 17:59
Are you still experiencing the bug in the same way? I tried to reproduce this and git opened a browser window for me to enter my credentials. After closing the window the command failed, because it couldn't open tty. Is this the same for you?

**Comment by timsofteng** [comment] 2021-06-15 18:17
@TimUntersberger btw what is `pushremote` means?

**Comment by TimUntersberger** [comment] 2021-06-15 18:32
Currently `pushremote` and `upstream` do the same thing. We copied this from magit. This is only relevant for forks. Basically upstream is the repo you forked from and upstream is your own fork.

**Comment by timsofteng** [comment] 2021-06-15 18:36
> Currently `pushremote` and `upstream` do the same thing. We copied this from magit. This is only relevant for forks. Basically upstream is the repo you forked from and upstream is your own fork.

I guess you typos. Upstream-upstream.

About issue. It still exist. Tried it minute ago. Pushing to `pushremote` freeze everything.

**Comment by TimUntersberger** [comment] 2021-06-15 18:41
Hmm. This is interesting. It also fails for me, but it doesn't freeze the application.

Are you using the terminal version or a gui version?

**Comment by timsofteng** [comment] 2021-06-15 19:23
> Hmm. This is interesting. It also fails for me, but it doesn't freeze the application.
> 
> Are you using the terminal version or a gui version?

terminal version.

neovim 0.5
Alacritty
Debian testing

**Comment by LeonGr** [comment] 2021-07-07 14:51
@TimUntersberger for me git immediately opens a tty, not a browser window. 
I think the application freezes because `neogit.process.spawn` doesn't return, because it's waiting for the tty process to close. Do you have any idea if a process started by `vim.loop.spawn` can accept user input? I tried but could not figure it out.

**Comment by TimUntersberger** [comment] 2021-07-14 16:03
This should be fixed in the latest version. We now parse the remote url and ask for any missing information.

Which means that a remote url like `http://test@github.com/x/x.git` will make neogit ask for the password
and `http://github.com/x/x.git` for the password and username.

The password will be replaced with `*` in the command history.

**Comment by jens1205** [comment] 2021-07-17 15:53
It looks like Neogit is not respecting the credential.helper settings of git. I'm asked for username / password although in my case osxkeychain is configured as credential.helper. Git on command-line and vim-fugitive are happy with this and are not asking for credentials, while neogit does.

**Comment by TimUntersberger** [comment] 2021-07-17 20:42
@jens1205 the current implementation is very hacky. #172 attempts to fix this.

**Comment by timsofteng** [comment] 2021-08-15 18:29
Tried to pull something from repo and issue still exists

**Comment by TimUntersberger** [comment] 2021-08-15 18:39
@timsofteng #172. I am currently debating whether to just merge the PR with a small bug or to wait until it is fixed.

**Comment by timsofteng** [comment] 2021-08-17 21:09
> @timsofteng #172. I am currently debating whether to just merge the PR with a small bug or to wait until it is fixed.

Oh. Got it.

**Comment by TimUntersberger** [comment] 2021-08-17 21:55
This should be fixed?

**Comment by timsofteng** [comment] 2021-08-18 20:52
> This should be fixed?

What do you mean?
When I tried it last time it didn't work.

**Comment by TimUntersberger** [comment] 2021-08-20 21:29
> But there is no info about it. Do i do something wrong?

The problem might be that the git process takes a bit to close, so the command entry only gets added after some delay. Can you try to see if the pull command is in the history after 4-5 seconds?

**Comment by CKolkey** [comment] 2023-07-30 09:45
Closing this - if it's still a problem, open a new issue.

**Closed by CKolkey** 2023-07-30 09:45 UTC
Labels: bug
