### ISSUE TITLE
neogit leaves behind another empty buffer every time its open

### ISSUE THREAD

**Issue by BeauSLM** [NeogitOrg/neogit#1289] opened 2024-05-13 03:27 UTC
### Description

opening neogit adds an empty buffer, closing neogit doesn't remove this buffer. they accumulate during use of neogit. especially problematic with tabs or other UI that works with buffers

### Neovim version

NVIM v0.10.0-dev-3107+g8c7a8be27
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info

### Operating system and version

macos 14.4.1

### Steps to reproduce

open neovim with any minimal repro (including the one provided by the issue template)

`:Neogit` then close with q or any other way

`:buffers` shows a no name buffer, keep opening neogit to add more buffers

### Expected behavior

no accumulation of no name buffers

### Actual behavior

accumulation of no name buffers

### Minimal config

```Lua
-- NOTE: See the end of this file if you are reporting an issue, etc. Ignore all the "scary" functions up top, those are
-- used for setup and other operations.
local M = {}

local base_root_path = vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":p:h") .. "/.min"
function M.root(path)
  return base_root_path .. "/" .. (path or "")
end

function M.load_plugin(plugin_name, plugin_url)
  local package_root = M.root("plugins/")
  local install_destination = package_root .. plugin_name
  vim.opt.runtimepath:append(install_destination)

  if not vim.loop.fs_stat(package_root) then
    vim.fn.mkdir(package_root, "p")
  end

  if not vim.loop.fs_stat(install_destination) then
    print(string.format("> Downloading plugin '%s' to '%s'", plugin_name, install_destination))
    vim.fn.system({
      "git",
      "clone",
      "--depth=1",
      plugin_url,
      install_destination,
    })
    if vim.v.shell_error > 0 then
      error(string.format("> Failed to clone plugin: '%s' in '%s'!", plugin_name, install_destination),
        vim.log.levels.ERROR)
    end
  end
end

---@alias PluginName string The plugin name, will be used as part of the git clone destination
---@alias PluginUrl string The git url at which a plugin is located, can be a path. See https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols for details
---@alias MinPlugins table<PluginName, PluginUrl>

---Do the initial setup. Downloads plugins, ensures the minimal init does not pollute the filesystem by keeping
---everything self contained to the CWD of the minimal init file. Run prior to running tests, reproducing issues, etc.
---@param plugins? table<PluginName, PluginUrl>
function M.setup(plugins)
  vim.opt.packpath = {}                      -- Empty the package path so we use only the plugins specified
  vim.opt.runtimepath:append(M.root(".min")) -- Ensure the runtime detects the root min dir

  -- Install required plugins
  if plugins ~= nil then
    for plugin_name, plugin_url in pairs(plugins) do
      M.load_plugin(plugin_name, plugin_url)
    end
  end

  vim.env.XDG_CONFIG_HOME = M.root("xdg/config")
  vim.env.XDG_DATA_HOME = M.root("xdg/data")
  vim.env.XDG_STATE_HOME = M.root("xdg/state")
  vim.env.XDG_CACHE_HOME = M.root("xdg/cache")

  -- NOTE: Cleanup the xdg cache on exit so new runs of the minimal init doesn't share any previous state, e.g. shada
  vim.api.nvim_create_autocmd("VimLeave", {
    callback = function()
      vim.fn.system({
        "rm",
        "-r",
        "-f",
        M.root("xdg")
      })
    end
  })
end

-- NOTE: If you have additional plugins you need to install to reproduce your issue, include them in the plugins
-- table within the setup call below.
M.setup({
  plenary = "https://github.com/nvim-lua/plenary.nvim.git",
  telescope = "https://github.com/nvim-telescope/telescope.nvim",
  diffview = "https://github.com/sindrets/diffview.nvim",
  neogit = "https://github.com/NeogitOrg/neogit"
})
-- WARN: Do all plugin setup, test runs, reproductions, etc. AFTER calling setup with a list of plugins!
-- Basically, do all that stuff AFTER this line.
require("neogit").setup({}) -- For instance, setup Neogit
```

**Comment by BeauSLM** [comment] 2024-05-16 16:56
this only happens on the nightly branch. easiest way i found to get there was to not clone with depth=1 and just check it out manually

**Comment by CKolkey** [comment] 2024-05-16 17:11
No worries, I found the issue.

**Comment by parga** [comment] 2024-05-16 22:28
this is also happening after upgrading to neovim 0.10, thanks @CKolkey in advance and looking forward for the fix

**Comment by ronisbr** [comment] 2024-05-24 02:41
Yes, I am having the same problem and it started when I upgraded to Neovim 0.10 (but it can be a coincidence). The temporary solution was to change `kind` to `replace`.

**Comment by kitallen23** [comment] 2024-05-24 03:02
I am also having this issue.

**Comment by konosubakonoakua** [comment] 2024-05-24 04:53
Me toooo. Hope be solved soon~ :D

**Comment by wkwhwh** [comment] 2024-05-24 09:57
Same, I tried the replace thing but it doesn't matter if you are doing a lot of git stuff as it creates buffers for anything you do inside Neogit.

**Comment by konosubakonoakua** [comment] 2024-05-24 09:59
```lua
keymap('n', '<leader>b.', function()
    local buffers = vim.api.nvim_list_bufs()
    for _, buf in ipairs(buffers) do
        if vim.api.nvim_buf_is_valid(buf) then
          local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, false)
          if #lines == 1 and #lines[1] == 0 then
          -- Buffer is empty, delete it
          vim.api.nvim_buf_delete(buf, { force = true })
        end
      end
    end
  end, { desc = "Delete all empty buffer", noremap = true, silent = true })

```

for emergency. :D

**Comment by CKolkey** [comment] 2024-05-24 13:47
If anyone still experiences this issue with the above fix merged, please let me know here. That said, I can reproduce the `no name` issue before, but not after, that patch.

**Comment by CKolkey** [comment] 2024-05-24 13:52
Shoot, really? With all kinds (split, tab, etc), or one specifically?

**Comment by wkwhwh** [comment] 2024-05-24 13:56
Still experiencing the same issue with no name buffers.

![CleanShot 2024-05-24 at 14 54 11](https://github.com/NeogitOrg/neogit/assets/7226788/ee80f1da-316b-4ba6-b15a-5f7ce904538d)

**Comment by CKolkey** [comment] 2024-05-24 13:57
Are you both using a buffer-line plugin? I'm using `:buffers` to check this.

**Comment by qRoC** [comment] 2024-05-24 13:58
I use tabline

**Comment by kitallen23** [comment] 2024-05-24 13:59
I am using bufferline and I am experiencing the same. Note that most empty buffers are gone; only the one from the main neogit instance is hanging about.

**Comment by qRoC** [comment] 2024-05-24 14:00
>> Note that most empty buffers are gone; only the one from the main neogit instance is hanging about.
<img width="189" alt="Screenshot 2024-05-24 at 17 00 28" src="https://github.com/NeogitOrg/neogit/assets/1789565/d5f0b045-0a05-45dc-9587-dba313d681ac">

**Comment by kitallen23** [comment] 2024-05-24 14:02
@qRoC Are you using any special `kind`, or the default?

**Comment by qRoC** [comment] 2024-05-24 14:04
default

**Comment by kitallen23** [comment] 2024-05-24 14:06
Ahh, I can in fact reproduce every time I open a new tab, e.g. `log_view` etc.

**Comment by wkwhwh** [comment] 2024-05-24 14:06
I am using default kind (tab), and I have lualine for my buffers, removing the setting to displaying buffer from lualine config still shows empty buffers being created. when I search buffers via telescope. For me nothing changed I still see buffers being created whenever I do any git related stuff inside neogit.

![CleanShot 2024-05-24 at 15 03 51@2x](https://github.com/NeogitOrg/neogit/assets/7226788/09e3c2c5-8f4b-41f4-afdd-a380266956d1)

**Comment by CKolkey** [comment] 2024-05-24 14:10
If someone could give this branch a try and let me know if the issue persists for them, I'd appreciate it :) https://github.com/NeogitOrg/neogit/pull/1326

**Comment by wkwhwh** [comment] 2024-05-24 14:15
unfortunately for me it's still behaving the same way on that branch

![CleanShot 2024-05-24 at 15 15 03@2x](https://github.com/NeogitOrg/neogit/assets/7226788/6c7fc515-ee70-4b5e-b63f-2097dfed5d84)

**Comment by kitallen23** [comment] 2024-05-24 14:16
> If someone could give this branch a try and let me know if the issue persists for them, I'd appreciate it :) #1326

Sorry to say but yes I'm still having the same issues :(

Thank you for all your efforts, it's appreciated!

**Comment by CKolkey** [comment] 2024-05-24 14:27
I tried setting up both Tabby and https://github.com/akinsho/bufferline.nvim and can't get it to show any noname buffers :\

Also tried with a very very minimal config and can't reproduce.

Happy to keep trying to fix this, but I think at this point I need a minimal reproduction config to actually work on it. If someone wants to make that, then I'll do what I can to fix it :)

**Comment by kitallen23** [comment] 2024-05-24 14:28
Here is mine, and for what it's worth, I'm on macOS.
```lua
require("neogit").setup {
    use_default_keymaps = true,
    integrations = {
        diffview = false,
    },
    commit_editor = {
        kind = "vsplit",
        show_staged_diff = false,
        staged_diff_split_kind = "split"
    },
}
```

**Comment by CKolkey** [comment] 2024-05-24 14:38
Alright, found a way to reproduce it! Thanks for the help, I'll try to fix this tonight after the kiddo is asleep

**Comment by ronisbr** [comment] 2024-05-24 16:03
Here, the new commit does not create anymore the empty buffer when opening the popup, but it does show if we open the commit message buffer.

**Comment by iH8c0ff33** [comment] 2024-05-25 13:35
@CKolkey the empty buffer seems to be created by tabnew. Replacing the call of tabnew (in `Buffer:show()`) with `tab sb <bufno>` solved the problem for me.

```diff
diff --git a/lua/neogit/lib/buffer.lua b/lua/neogit/lib/buffer.lua
index 42c14789..c70f522e 100644
--- a/lua/neogit/lib/buffer.lua
+++ b/lua/neogit/lib/buffer.lua
@@ -258,8 +258,7 @@ function Buffer:show()
     api.nvim_set_current_buf(self.handle)
     win = api.nvim_get_current_win()
   elseif kind == "tab" then
-    vim.cmd("tabnew")
-    api.nvim_set_current_buf(self.handle)
+    vim.cmd("tab sb " .. self.handle)
     win = api.nvim_get_current_win()
   elseif kind == "split" then
     win = api.nvim_open_win(self.handle, true, { split = "below" })
```

**Comment by wkwhwh** [comment] 2024-05-25 17:01
the fix from @iH8c0ff33  also solved the problem for me.

**Comment by CKolkey** [comment] 2024-05-25 18:49
Awesome - I'll have it shipped in a few minutes. Thank you @iH8c0ff33 !

**Closed** 2024-05-25 19:00 UTC
Labels: bug

**Comment by qRoC** [comment] 2024-05-26 07:38
@CKolkey new problem :)

1. Run `Neogit` - this create new tab
2. Close this tab - This close my buffer

https://github.com/NeogitOrg/neogit/assets/1789565/a4dcad38-7233-413b-9a2b-7f623b7cff31

**Comment by qRoC** [comment] 2024-05-26 07:48
depends on CWD

**Comment by qRoC** [comment] 2024-05-26 07:51
https://github.com/NeogitOrg/neogit/assets/1789565/ba35fb12-ae2d-49a3-82e0-bceecde2e3ec

**Comment by CKolkey** [comment] 2024-05-26 09:17
guys, I've got a 2 year old and my wife is pregnant - _feel free to submit a PR_ 😅

Anyways, I appreciate the patience otherwise :)

**Comment by ilias777** [comment] 2024-05-26 20:21
The fix works for me. No any empty buffers.

**Comment by stevenxxiu** [comment] 2024-10-04 16:38
This is happening for me again.

One commit that causes this is <https://github.com/NeogitOrg/neogit/commit/d639f5a5bd1f609d6a466b18a1c1e572bb7308bd>.

Patching it this way closes them:

```diff
diff --git a/lua/neogit/lib/buffer.lua b/lua/neogit/lib/buffer.lua
index add3d56f..c074070c 100644
--- a/lua/neogit/lib/buffer.lua
+++ b/lua/neogit/lib/buffer.lua
@@ -209,7 +209,7 @@ function Buffer:close(force)
   if self.kind == "tab" then
     local ok, _ = pcall(vim.cmd, "tabclose")
     if not ok then
-      vim.cmd("tabnew")
+      vim.cmd("tab sb " .. self.handle)
       vim.cmd("tabclose #")
     end
 
@@ -279,7 +279,7 @@ function Buffer:show()
     api.nvim_set_current_buf(self.handle)
     win = api.nvim_get_current_win()
   elseif kind == "tab" then
-    vim.cmd("$tabnew")
+    vim.cmd("tab sb " .. self.handle)
     api.nvim_set_current_buf(self.handle)
     win = api.nvim_get_current_win()
   elseif kind == "split" or kind == "split_below" then
```
