### ISSUE TITLE
Option to opt-out spinners

### ISSUE THREAD

**Issue by s-cerevisiae** [NeogitOrg/neogit#1577] opened 2024-11-28 13:45 UTC
**Is your feature request related to a problem? Please describe.**

The newly-added spinner doesn't work well when the remote is long and/or the screen is small: if it's longer than a line then "Press Enter to continue" will show up on *each frame*, making it unusable.

**Describe the solution you'd like**

An option that turns the spinner off.

**Describe alternatives you've considered**

Somehow don't make it trigger the overflow popup?

A way to direct it to fidget.nvim should also make it work for my personal case.

**Comment by CKolkey** [comment] 2024-11-28 14:22
Oh, shit, that sucks. There's already an opt-out (progress_spinner), but I'll add some logic to check window width and truncate it. Thanks for letting me know.

**Comment by CKolkey** [comment] 2024-11-28 14:23
I'm open to some kind of fidget integration. Lemme see about that.

**Comment by ktsujister** [comment] 2024-12-03 02:13
> Yes, but that doesn't include the spinner, which is always displayed in the command line.

Got it. Yes, that won't solve this spinner + window width issue you are describing, so it was kind of off-topic. My bad.

**Comment by Allaman** [comment] 2024-12-04 18:14
> Oh, shit, that sucks. There's already an opt-out (progress_spinner), but I'll add some logic to check window width and truncate it. Thanks for letting me know.

Hello, can you please give more details how to opt-out? I couldn't find information in the docs and the code :(

Background: Whenever I save a commit message, an unnamed buffer containing `⠙ git commit` is open which is quite frustrating. I want to exclude the spinners as the root cause for this behavior.

Thanks (a former Magit user)

**Comment by CKolkey** [comment] 2024-12-04 20:43
You can set `neogit.setup({ process_spinner = false })` when you setup the plugin :)

**Comment by CKolkey** [comment] 2024-12-04 23:20
Just merged some truncation logic - feel free to reopen if there are still issues

**Closed by CKolkey** 2024-12-04 23:20 UTC
