### ISSUE TITLE
diffview colors are gone

### ISSUE THREAD

**Issue by fdelacruz** [NeogitOrg/neogit#600] opened 2023-07-15 10:34 UTC
### Description

Suddenly there are no diffview colors 

<img width="529" alt="Screen Shot 2023-07-15 at 12 23 53 PM" src="https://github.com/NeogitOrg/neogit/assets/148098/fa2a305b-6ded-4e27-a631-58b785cf99fb">

### Neovim version

NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

macOS 10.15.7

### Steps to reproduce

call neogit

### Expected behavior

Colors displayed in NeogitStatus

### Actual behavior

NO Colors displayed in NeogitStatus

**Comment by CKolkey** [comment] 2023-07-15 10:38
If you load the colorscheme _after_ neogit, then we can't build our colors. In that case, you'll need to make sure your colorscheme supports all our highlight groups, which it might not since we recently added many. I'd recommend either making sure your colorscheme is loaded first, or open an issue on your colorscheme's repo.

**Comment by fdelacruz** [comment] 2023-07-15 12:40
Well, I can report that [kanagawa](https://github.com/rebelot/kanagawa.nvim) supports the hightlights while [catppuccin](https://github.com/catppuccin/catppuccin) does not. 
I tried loading loading it before to no avail.

**Comment by fdelacruz** [comment] 2023-07-15 12:43
This was working fine until recently though I couldn't which  update.

**Comment by treatybreaker** [comment] 2023-07-15 15:26
@fdelacruz 

I'm using Catppuccin now and I am unable to replicate. Nor am I able to replicate in Kanagawa.

Wherever you're passing your colorscheme to your package manager ensure it is loading in first.

For instance if you're using `lazy` as your package manager, set the priority for the colorscheme plugin to a really high number, e.g. `1000` so it loads first.

**Comment by francescarpi** [comment] 2023-07-15 17:01
Hi. I've got the same problem using "tanvirtin/monokai.nvim" theme. The colors are gone.

**Comment by fdelacruz** [comment] 2023-07-15 19:36
I've been loading my neogit setup from a config.lua file
`reload "user.neogit"`

```
local neogit = require "neogit"

neogit.setup {
  disable_signs = false,
  disable_hint = true,
  disable_context_highlighting = false,
  disable_commit_confirmation = true,
  -- Neogit refreshes its internal state after specific events, which can be expensive depending on the repository size.
  -- Disabling `auto_refresh` will make it so you have to manually refresh the status after you open it.
  auto_refresh = true,
  disable_builtin_notifications = false,
  use_magit_keybindings = false,
  -- Change the default way of opening neogit
  kind = "tab",
  -- Change the default way of opening the commit popup
  commit_popup = {
    kind = "split",
  },
  -- Change the default way of opening popups
  popup = {
    kind = "split",
  },
  -- customize displayed signs
  signs = {
    -- { CLOSED, OPENED }
    section = { ">", "v" },
    item = { ">", "v" },
    hunk = { "", "" },
  },
  integrations = {
    diffview = true,
  },
  -- Setting any section to `false` will make the section not render at all
  sections = {
    untracked = {
      folded = false,
    },
    unstaged = {
      folded = false,
    },
    staged = {
      folded = false,
    },
    stashes = {
      folded = true,
    },
    unpulled = {
      folded = true,
    },
    unmerged = {
      folded = false,
    },
    recent = {
      folded = true,
    },
  },
  -- override/add mappings
  mappings = {
    -- modify status buffer mappings
    status = {
      ["q"] = "Close",
      ["1"] = "Depth1",
      ["2"] = "Depth2",
      ["3"] = "Depth3",
      ["4"] = "Depth4",
      ["<tab>"] = "Toggle",
      ["x"] = "Discard",
      ["s"] = "Stage",
      ["a"] = "StageUnstaged",
      ["<c-s>"] = "StageAll",
      ["u"] = "Unstage",
      ["U"] = "UnstageStaged",
      ["d"] = "DiffAtFile",
      ["$"] = "CommandHistory",
      ["<c-r>"] = "RefreshBuffer",
      ["o"] = "GoToFile",
      ["<enter>"] = "Toggle",
      ["<c-v>"] = "VSplitOpen",
      ["<c-x>"] = "SplitOpen",
      ["<c-t>"] = "TabOpen",
      ["?"] = "HelpPopup",
      ["D"] = "DiffPopup",
      ["p"] = "PullPopup",
      ["r"] = "RebasePopup",
      ["P"] = "PushPopup",
      ["c"] = "CommitPopup",
      ["L"] = "LogPopup",
      ["Z"] = "StashPopup",
      ["b"] = "BranchPopup",
      -- ["<space>"] = "Stage",
      -- Removes the default mapping of "s"
      -- ["s"] = "",
    },
  },
}

```
As soon as I comment out that line colors work beautifully
<img width="566" alt="Screen Shot 2023-07-15 at 9 35 09 PM" src="https://github.com/NeogitOrg/neogit/assets/148098/c4373db7-abe4-458e-aed1-2b3ddb299509">

**Comment by katawful** [comment] 2023-07-15 20:48
> If you load the colorscheme _after_ neogit, then we can't build our colors. In that case, you'll need to make sure your colorscheme supports all our highlight groups, which it might not since we recently added many. I'd recommend either making sure your colorscheme is loaded first, or open an issue on your colorscheme's repo.

Why can't you use a `autocmd ColorScheme` here? It would solve this and #590 

Also I find that relying on colorscheme behavior *at all* is a poor design choice and sensible defaults (both builtin hl-groups and hardcoded colors) to be far more reasonable. Plugins such as rainbow-delimiters and gitsigns both do this. Colorschemes can of course modify plugin highlights as needed, but expecting it in the fallback will always leave these issues open no matter what

**Comment by CKolkey** [comment] 2023-07-15 20:53
Yeah, maybe it wasn't a good choice. I wanted it to "just work" for people out of the box, but it sounds like it's not quite working as I had hoped. I don't mind just hard-coding things, so, maybe thats the move.

**Comment by CKolkey** [comment] 2023-07-15 21:04
Lemme know if this branch fixes things, or if I should do more: https://github.com/NeogitOrg/neogit/pull/617

**Comment by fdelacruz** [comment] 2023-07-15 21:43
Still not working, unless i comment out the config.lua line.

**Comment by francescarpi** [comment] 2023-07-16 06:24
Same here. Trying the "hard-code-colors" branch, still not working.
Thanks

**Comment by francescarpi** [comment] 2023-07-16 06:55
Finally, I've forced set neogit colors after monokai theme is loaded and it looks nice for me.

<img width="1203" alt="image" src="https://github.com/NeogitOrg/neogit/assets/287872/f5b3eaeb-310d-42e1-b230-c582a9f991f1">

**Comment by CKolkey** [comment] 2023-07-16 08:09
Alright. If someone makes me a minimal setup that reproduces it, I'll look into this more. But long term, open a PR/issue with your colorscheme to add the missing highlight groups.

**Comment by fdelacruz** [comment] 2023-07-16 11:09
@CKolkey catppucin obviously supports neogit's hl groups. 
Perhaps is the way lunarvim loads stuff, in my case at least.

**Comment by CKolkey** [comment] 2023-07-16 11:45
We recently added a ton of new highlight groups, so it's possible they do not do that yet.

**Comment by fdelacruz** [comment] 2023-07-16 13:00
@CKolkey can you please share the commit where these hightlight groups were added?
Just to check.

**Comment by fdelacruz** [comment] 2023-07-16 13:37
The following seems to do the trick:
```
  {
    "catppuccin/nvim",
    name = "catppuccin",
    priority = 1000,
    config = function ()
      require("catppuccin").setup {
        integrations = {
          neogit = true,
        }
      }
    end
  },

```
<img width="701" alt="Screen Shot 2023-07-16 at 3 28 19 PM" src="https://github.com/NeogitOrg/neogit/assets/148098/f92a0bec-1525-4386-9279-8b8879ac9d9a">

Though not fully as here:
<img width="785" alt="Screen Shot 2023-07-16 at 3 36 13 PM" src="https://github.com/NeogitOrg/neogit/assets/148098/7151f404-5bf2-4e8d-a3db-6d6c73a0a16b">

**Comment by fdelacruz** [comment] 2023-07-16 15:43
_Never a dull moment_ 
Just in time before my wife almost had to drag me out to enjoy Berlin’s summer.

**Comment by ten3roberts** [comment] 2023-07-17 10:21
If the sections are green it is before *The Merge*.

They were previously highlighted using the `Function` highlight, rather than our own `Neogit{...}` hl group

**Comment by CKolkey** [comment] 2023-07-17 11:37
Love that name. We're very recently merged about six months of work, along with restructuring as an org. The screenshots are a little outdated - I need to spend a little time on the readme, but family is in town so... that'll just wait 😋

**Comment by CKolkey** [comment] 2023-07-17 21:05
```
:hi-link

When you want to use the same highlighting for several syntax groups, you
can do this more easily by linking the groups into one common highlight
group, and give the color attributes only for that group.
```

As far as I can see, it basically says "just use the definition for that one"

**Closed** 2023-07-17 21:23 UTC
Labels: bug

**Comment by francescarpi** [comment] 2023-07-18 19:13
Amazing team. Thank you so much. I just updated the plugin and the colors are pretty cool with the monokai theme.
Great job.

**Comment by eins** [comment] 2024-02-11 00:15
> Temporally, I've forced set neogit colors after monokai theme is loaded and it looks nice for me.
> 
> ```lua
> local monokai = require('monokai')
> 
> vim.cmd [[colorscheme monokai]]
> 
> ------------------------------------------------------------------------------
> -- Neogit
> vim.api.nvim_set_hl(0, "NeogitStagedchanges", { fg = monokai.classic.aqua, bg = monokai.classic.base0 })          -- Unstaged changes
> vim.api.nvim_set_hl(0, "NeogitUnstagedchanges", { fg = monokai.classic.aqua, bg = monokai.classic.base0 })        -- Unstaged changes
> vim.api.nvim_set_hl(0, "NeogitRecentCommits", { fg = monokai.classic.aqua, bg = monokai.classic.base0 })          -- Recent commits
> vim.api.nvim_set_hl(0, "NeogitBranch", { fg = monokai.classic.yellow, bg = monokai.classic.base0 })               -- Head branch
> vim.api.nvim_set_hl(0, "NeogitRemote", { fg = monokai.classic.yellow, bg = monokai.classic.base0 })               -- Push branch
> 
> vim.api.nvim_set_hl(0, "NeogitDiffAddHighlight", { fg = monokai.classic.green, bg = monokai.classic.base0 })      -- Added
> vim.api.nvim_set_hl(0, "NeogitDiffDeleteHighlight", { fg = monokai.classic.pink, bg = monokai.classic.base0 })    -- Removed
> 
> vim.api.nvim_set_hl(0, "NeogitHunkHeader", { fg = monokai.classic.orange, bg = monokai.classic.base0 })           -- Header
> vim.api.nvim_set_hl(0, "NeogitHunkHeaderHighlight", { fg = monokai.classic.orange, bg = monokai.classic.base0 })  -- Header highlighted
> ```
> 
> <img alt="image" width="1192" src="https://private-user-images.githubusercontent.com/287872/253789487-a889a023-f478-4d9f-9605-322e834caf5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MTAzNTAsIm5iZiI6MTcwNzYxMDA1MCwicGF0aCI6Ii8yODc4NzIvMjUzNzg5NDg3LWE4ODlhMDIzLWY0NzgtNGQ5Zi05NjA1LTMyMmU4MzRjYWY1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQwMDA3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMGE5MjAyNmQ1MWFiZGRiZmFmYzM0NzEzNWU1MTg1OTc1MDM5MjVkN2M1ZTEyZmRiNDkwNWQ5MDMxMGUxMGRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FEyGelE2_4FZufxWPAwayyVNqFIocGTRHT0puinJSf4">

@francescarpi thanks for posting this.

I'm using `'tanvirtin/monokai.nvim' and Neogit isn't showing the proper colors for any of the commands.  

I tested the line of code that you wrote and it worked it. 

What do you mean with temporally?
I want to understand if I need to define the colorscheme monokai like you did or there is a setting for it.
