### ISSUE TITLE
Invalid buffer id

### ISSUE THREAD

**Issue by Shatur** [NeogitOrg/neogit#235] opened 2021-10-26 18:45 UTC
### Description

Once the commit or stash preview buffer is closed, it can no longer be reopened.

### Neovim version

NVIM v0.5.1
Build type: Release
LuaJIT 2.0.5

### Operating system and version

ArchLinux

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. `:Neogit`
3. Open any commit by navigation to it end pressing <Enter>
4. `:q`
5. Open commit view again.

### Expected behavior

Commit view opened again.

### Actual behavior

```
Error executing vim.schedule lua callback: ...k/plugins/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...nvim/pack/plugins/start/neogit/lua/neogit/lib/buffer.lua:85: Invalid buffer id: 8
```

But if you press the `<Enter>` button again - it will work. So I need to press `<Enter>` twice after first open.

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "TimUntersberger/neogit",
        requires = {
          { "nvim-lua/plenary.nvim" },
          { "sindrets/diffview.nvim" },
        },
        config = function()
          print("loaded neogit")
          require("neogit").setup()
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing neogit and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
```

**Comment by TimUntersberger** [comment] 2021-11-15 14:09
@Shatur did the commit fix it for you?

**Comment by Shatur** [comment] 2021-11-15 14:24
It works, thanks! But after closing, the cursor is moved to the window with the code, not to the Neogit menu. Is this expected?

**Comment by kunzaatko** [comment] 2022-03-09 09:40
I have a similar problem that is however triggered by the internal `diagnostics` module. It shows when closing the _commit window_ in `neogit`. Do you have any idea about what can be causing this?

>Error executing vim.schedule lua callback: ...pack/packer/opt/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: /usr/share/nvim/runtime/lua/vim/diagnostic.lua:51: Invalid buffer id: 27
>stack traceback:
>       [C]: in function 'error'
>        ...pack/packer/opt/plenary.nvim/lua/plenary/async/async.lua:14: in function 'callback_or_next'
>        ...pack/packer/opt/plenary.nvim/lua/plenary/async/async.lua:40: in function <...pack/packer/opt/plenary.nvim/lua/plenary/async/async.lua:39>

**Comment by n3wborn** [comment] 2022-03-22 10:49
Same problem here when in NeogitStatus window I hit "enter" to see a commit details, or when I finished to write a commit message. 

NVIM v0.7.0-dev+1292-ge9b53f3fb
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by weilbith** [comment] 2022-07-08 09:20
Same problem. After I closed the Neogit status tab NeoVim becomes unusable too me due to continuous errors. Not reproducible with minimal config. But I have no clue at all what it can be.

**Comment by CKolkey** [comment] 2023-09-26 19:52
This seems to be working now - feel free to reopen if thats not the case.

**Closed by CKolkey** 2023-09-26 19:52 UTC
Labels: bug
