### ISSUE TITLE
Neogit doesn't see git files

### ISSUE THREAD

**Issue by TakenMC** [NeogitOrg/neogit#538] opened 2023-06-23 18:30 UTC
### Description

Neogit would show this message every time when I try to open it but the .git dir is already in the directory so I am not sure what is happening
![image](https://github.com/TimUntersberger/neogit/assets/68560840/aee97b25-b617-4eeb-9164-3f3f199107a6)

### Neovim version

NVIM v0.9.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system and version

Windows 10

### Steps to reproduce

1. I just open Neogit using the command

### Expected behavior

For it to stop prompting me to init a git repo in a git directory

### Actual behavior

It keeps prompting me to git init in a git local repo

### Minimal config

```Lua
local setup, neogit = pcall(require, "neogit")
if not setup then
    return
end

neogit.setup {
    auto_refresh = true,
    remember_settings = true,
    ignored_settings = {},
    disable_insert_on_commit = false,
    commit_popup = {
        kind = "split",
    },
    preview_buffer = {
        kind = "split",
    },
    popup = {
        kind = "split",
    },
    signs = {
        section = { ">", "v" },
        item = { ">", "v" },
        hunk = { "", "" },
    },
    integrations = {
        diffview = true
    },
    sections = {
        untracked = {
            folded = false
        },
        unstaged = {
            folded = false
        },
        staged = {
            folded = false
        },
        stashes = {
            folded = true
        },
        unpulled = {
            folded = true
        },
        unmerged = {
            folded = false
        },
        recent = {
            folded = true
        },
    },
    mappings = {
        status = {
            ["p"] = "PushPopup",
            ["P"] = "PullPopup"
        }
    }
}
```

**Comment by wrightjjw** [comment] 2023-06-23 18:59
Fellow Windows user here. I'm not able to reproduce this. Does this happen in every git repo you open?

Open to suggestions from other watchers... I'm not super familiar with neogit's codebase.

**Comment by CKolkey** [comment] 2023-06-23 19:03
So, here's the relevant bit that does the check on open: https://github.com/TimUntersberger/neogit/blob/master/lua/neogit.lua#L29

And _here's_ the command it's running: https://github.com/TimUntersberger/neogit/blob/master/lua/neogit/lib/git/cli.lua#L329

Could you run that command and let us know the output?

**Comment by TakenMC** [comment] 2023-06-23 19:31
It returns true

**Comment by TakenMC** [comment] 2023-06-23 19:32
and it returns true on multiple repos as well

**Comment by TakenMC** [comment] 2023-06-23 19:35
![image](https://github.com/TimUntersberger/neogit/assets/68560840/ebf5aaae-e17f-456e-81f6-0d66ff2b8f5f)

**Comment by wrightjjw** [comment] 2023-06-23 19:54
I notice your Neovim is using backslashes, but your shell is using forward slashes. Do you happen to be running your shell through WSL and your Neovim on Windows?

If so - Neogit is trying to use your Windows git and the shell is likely using your WSL git. Try the same commands using `git.exe` to use the Windows git.

**Comment by TakenMC** [comment] 2023-06-23 20:05
That is just formating by oh my posh

**Comment by TakenMC** [comment] 2023-06-23 20:05
Tho git blame also seems to not work

**Comment by CKolkey** [comment] 2023-06-23 20:50
I have a feeling @wrightjjw might be on to something. Can you make absolutely certain this isn't a windows/wsl thing? Maybe try calling git via neovim: `:!git rev-parse --is-inside-work-tree`

Also, could you elaborate on what you mean by "git blame doesn't work" Whats its output, exactly?

**Comment by TakenMC** [comment] 2023-06-23 21:34
Git blame would usually show who commited each line in a file but it just doesn't work either

It could be just my pc cause on my laptop i remember it working

**Comment by TakenMC** [comment] 2023-06-23 21:34
Also i mean git blame the plugin

**Comment by TakenMC** [comment] 2023-06-23 21:51
I'll try that command on my pc tommorow

**Comment by wrightjjw** [comment] 2023-06-23 22:01
Running through oh-my-posh should be using Windows, so probably not a WSL thing.

This is definitely a weird one. I would definitely try the command through Neovim like @CKolkey suggested. It seems like there's a disconnect between Neovim and git, since other git plugins aren't working. Maybe it would be worth trying it through Lua too.

**Comment by TakenMC** [comment] 2023-06-23 22:05
Thru lua?

**Comment by wrightjjw** [comment] 2023-06-23 22:09
Yeah, doing something like `:lua print(vim.fn.system("git rev-parse --is-inside-work-tree"))`, which *should* be doing the same thing Neogit is.

**Comment by TakenMC** [comment] 2023-06-23 22:13
I'll try that tommorow

**Comment by TakenMC** [comment] 2023-06-24 06:44
> !git rev-parse --is-inside-work-tree

![image](https://github.com/TimUntersberger/neogit/assets/68560840/4b731071-6051-4544-8fbb-f3bcaceaa96e)

**Comment by TakenMC** [comment] 2023-06-24 06:48
Well I found the reason to why it's not working.
I had set an env var SHELL to pwsh.exe for another plugin.

**Comment by wrightjjw** [comment] 2023-06-26 11:24
Interesting. My `SHELL` and `COMSPEC` are unset, but looks like neovim automatically sets `shell` to cmd.exe. This may be a Neovim bug then?

**Comment by TakenMC** [comment] 2023-06-28 10:07
Mhm

**Comment by wrightjjw** [comment] 2023-07-05 21:38
@ten3roberts I think this can be closed. Doesn't seem like a Neogit issue.

**Comment by ten3roberts** [comment] 2023-07-06 08:07
Ok, thanks. I thought so as well but wasn't sure. Mainly about the path apparently being configured *inside* neogit.

I'll close it for now, but if it seems to be an issue on our side feel free to reopen it.

**Closed by ten3roberts** 2023-07-06 08:07 UTC
Labels: bug
