### ISSUE TITLE
Commit Popup

### ISSUE THREAD

**Issue by TimUntersberger** [NeogitOrg/neogit#15] opened 2020-09-16 19:04 UTC
### Actions

- [x] Commit
- [x] Extend
- [x] Reword
- [x] Amend
- [x] Fixup
- [x] Squash
- [x] Augment
- [x] Instant Fixup
- [x] Instant Squash

**Comment by faerryn** [comment] 2021-03-09 05:41
Feature request: Commit on Write

I've been using Neogit, and I can say I really like it over fugitive, since Neogit is much more keyboard-driven. Thank you for making this for the community!

I'm wondering if there is a way to configure Neogit so that the `control-c control-c` binding is applied on buffer write?

For example, I could write up a commit message and then go into normal mode, and type `:w`, thereby applying the commit

Another example: I could write a commit message and press `ZZ` in normal mode, thereby applying the commit. `ZZ` is short for `:wq` in vim.

**Comment by n3wborn** [comment] 2021-06-20 15:49
> ### Actions
> 
>     * [x]  Commit
> 
>     * [x]  Extend
> 
>     * [x]  Reword
> 
>     * [x]  Amend
> 
>     * [ ]  Fixup
> 
>     * [ ]  Squash
> 
>     * [ ]  Augment
> 
>     * [ ]  Instant Fixup
> 
>     * [ ]  Instant Squash

Hi !
As a newcomer I was about to fill an issue because I tried to "Fixup" a commit in the previous one but nothing happened when after "c" I hit "f" (same for f/s/S).

I though this was bug or me not being smart enough to understand how to do a fixup. I first asked on [r/neovim](https://www.reddit.com/r/neovim/comments/o465z0/neogit_how_to_fixupsquash/) and I've been told to fill an issue so that I and other people in the same situation could benefit from the answer. 

But now that I see this issue I can see that Fixup/Squash/etc is not possible yet. Maybe listing only available commands in commit popup could avoid useless issues and make things clearer to the user. 

I've just switched from fugitive cause I really love the way Neogit works, so thank you :)

**Comment by TimUntersberger** [comment] 2021-06-20 16:09
> Maybe listing only available commands in commit popup could avoid useless issues and make things clearer to the user.

I also noticed this problem. After #131 is merged this is fixed.

**Comment by hdonnay** [comment] 2021-08-11 17:22
Toggling a flag in the commit popup doesn't seem to do anything, or I'm misunderstanding what pressing `tab` on one of those lines means.

**Comment by n3wborn** [comment] 2021-08-11 17:36
> Toggling a flag in the commit popup doesn't seem to do anything, or I'm misunderstanding what pressing `tab` on one of those lines means.

Nvim nightly  / neogit up-to-date

Tabs on an option works for me, same if I type `-u` for upstream for exemple

**Comment by hdonnay** [comment] 2021-08-11 18:25
On neogit `3226b98` and neovim 0.5.0 (from Fedora 34) hitting the `-s` (signoff) toggle results in a message where the sign-off trailer is not present.

**Comment by TimUntersberger** [comment] 2021-08-13 09:24
@hdonnay I cannot reproduce this. If you open your command history, does it have the following line?

`git commit --file=.git/NEOGIT_COMMIT_EDITMSG --signoff`

**Comment by hdonnay** [comment] 2021-08-18 16:57
Ah, sorry, I was thrown off by the trailer not being there while editing, as if I'd run `git commit -s` on the command line. I do see that line in the command history and the trailer in the commit with `git show`. I must have been mistaken before when I thought it was missing. Thanks for the help!

**Comment by d-miketa** [comment] 2021-09-01 22:58
Hey, really enjoying this functionality. :)

I noticed one inconsistency though: when committing through `:Neogit commit`, I usually don't see a list of staged files etc to provide context for the commit message – but sometimes it appears. Committing via the UI at `:Neogit` always produces the list.

**Comment by TimUntersberger** [comment] 2021-09-02 16:59
> I usually don't see a list of staged files etc to provide context for the commit message

We are using the output of `git commit --dry-run` for that. I haven't reproduced this yet. If you encounter this again try running the command and see whether it includes the diff.

**Comment by d-miketa** [comment] 2021-09-02 20:13
I haven't encountered the error at all today, so perhaps one of your recent commits fixed it? :)

Thank you for the amazing plugin! Using it daily.

**Comment by pbogut** [comment] 2021-09-22 09:14
Not sure if its right place but its related. I don't get context for commit either, but only sometimes, not sure what it depends on, is all right in some projects in others its not.

What I can tell for sure is that when it doesn't work `git commit --dry-run` returns Error 128 in Neogit command log (after checking with `$`). Error 128 is `fatal: this operation must be run in a work tree`. When I run it manually `:execute('!cd ' . getcwd() . ' && git commit --dry-run')` it runs fine.

It looks like Neogit sometimes run this command outiside git tree.

**Comment by TimUntersberger** [comment] 2021-09-22 22:34
@pbogut can you create a seperate issue for this? Thank you for finding a problem 👍

**Comment by pbogut** [comment] 2021-09-23 09:14
@TimUntersberger I've tried to reproduce it with minimal config and it looks like it was my config. Sorry for bothering you. I will try to find out which part of my config was causing the issue and if it's not me being dumb (unlikely) I will create issue.

**Comment by vendion** [comment] 2022-08-05 03:26
When trying to do a commit using the verbose flag `-v`, there is no inline diff of the files that are about to be committed.

Also is it possible to set defaults for the commit popup? I like doing commits with the `-v` and `-s` flags and having to press them every time can get annoying.

**Closed** 2023-08-09 11:07 UTC
Labels: umbrella
